services:
  postgres-db:
    container_name: teslo-shop-postgres-db
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgres/data
    ports:
      - 5432:5432